# Generated by Django 4.1.1 on 2022-09-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todo_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
